"""background color

Revision ID: 04cde41bbf50
Revises: 76430f0ce204
Create Date: 2024-05-28 23:20:37.600658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cave_bot.const import SERVER_DEFAULT_USER_CONFIG


# revision identifiers, used by Alembic.
revision: str = '04cde41bbf50'
down_revision: Union[str, None] = '76430f0ce204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('background_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['background_color']))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_config', 'background_color')