"""background_border color

Revision ID: 9189e7d7e494
Revises: 04cde41bbf50
Create Date: 2024-05-29 14:52:21.129091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cave_bot.const import SERVER_DEFAULT_USER_CONFIG

# revision identifiers, used by Alembic.
revision: str = '9189e7d7e494'
down_revision: Union[str, None] = '04cde41bbf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('background_border_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['background_border_color']))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_config', 'background_border_color')