"""add map_size to map_type

Revision ID: a8f899de8563
Revises: fde7a62d363e
Create Date: 2024-05-16 17:59:56.275495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import cave_bot
from cave_bot.const import MapType
# revision identifiers, used by Alembic.
revision: str = 'a8f899de8563'
down_revision: Union[str, None] = 'fde7a62d363e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cell_13_05_2024', 'map_size', new_column_name = 'map_type')
    op.alter_column('user_record_13_05_2024', 'map_size', new_column_name = 'map_type')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cell_13_05_2024', 'map_type', new_column_name = 'map_size')
    op.alter_column('user_record_13_05_2024', 'map_type', new_column_name = 'map_size')

    # ### end Alembic commands ###
