"""text_color_to_user_config_and_color_scheme

Revision ID: b99d7a3e2867
Revises: 9189e7d7e494
Create Date: 2024-05-29 21:36:07.474972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cave_bot.const import SERVER_DEFAULT_USER_CONFIG


# revision identifiers, used by Alembic.
revision: str = 'b99d7a3e2867'
down_revision: Union[str, None] = '9189e7d7e494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_scheme', sa.Column('text_light_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_light_color']))
    op.add_column('color_scheme', sa.Column('text_dark_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_dark_color']))
    op.add_column('color_scheme', sa.Column('text_dark_light_threshold', sa.Integer(), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_dark_light_threshold']))
    op.add_column('color_scheme', sa.Column('text_all_collected_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_all_collected_color']))
    op.add_column('color_scheme', sa.Column('text_part_collected_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_part_collected_color']))
    op.add_column('color_scheme', sa.Column('progress_bar_background_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['progress_bar_background_color']))
    op.add_column('color_scheme', sa.Column('cell_background_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_background_color']))
    op.add_column('color_scheme', sa.Column('cell_background_border_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_background_border_color']))
    op.add_column('color_scheme', sa.Column('cell_icon', sa.Boolean(), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_icon']))
    
    op.add_column('user_config', sa.Column('text_light_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_light_color']))
    op.add_column('user_config', sa.Column('text_dark_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_dark_color']))
    op.add_column('user_config', sa.Column('text_dark_light_threshold', sa.Integer(), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_dark_light_threshold']))
    op.add_column('user_config', sa.Column('text_all_collected_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_all_collected_color']))
    op.add_column('user_config', sa.Column('text_part_collected_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['text_part_collected_color']))
    op.add_column('user_config', sa.Column('progress_bar_background_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['progress_bar_background_color']))
    op.add_column('user_config', sa.Column('cell_background_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_background_color']))
    op.add_column('user_config', sa.Column('cell_background_border_color', sa.String(length=15), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_background_border_color']))
    op.add_column('user_config', sa.Column('cell_icon', sa.Boolean(), nullable=False, server_default = SERVER_DEFAULT_USER_CONFIG['cell_icon']))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_config', 'text_part_collected_color')
    op.drop_column('user_config', 'text_all_collected_color')
    op.drop_column('user_config', 'text_dark_light_threshold')
    op.drop_column('user_config', 'text_dark_color')
    op.drop_column('user_config', 'text_light_color')
    op.drop_column('user_config', 'progress_bar_background_color')
    op.drop_column('user_config', 'cell_background_color')
    op.drop_column('user_config', 'cell_background_border_color')
    op.drop_column('user_config', 'cell_icon')
   
    op.drop_column('color_scheme', 'text_part_collected_color')
    op.drop_column('color_scheme', 'text_all_collected_color')
    op.drop_column('color_scheme', 'text_dark_light_threshold')
    op.drop_column('color_scheme', 'text_dark_color')
    op.drop_column('color_scheme', 'text_light_color')
    op.drop_column('color_scheme', 'progress_bar_background_color')
    op.drop_column('color_scheme', 'cell_background_color')
    op.drop_column('color_scheme', 'cell_background_border_color')
    op.drop_column('color_scheme', 'cell_icon')
    # ### end Alembic commands ###
