"""rename map to map_size

Revision ID: fde7a62d363e
Revises: bc34730301e3
Create Date: 2024-05-15 01:21:56.963585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde7a62d363e'
down_revision: Union[str, None] = 'bc34730301e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell_13_05_2024', 'map')
    op.drop_column('user_record_13_05_2024', 'map')
    op.add_column('cell_13_05_2024', sa.Column('map_size', sa.Integer(), nullable=False, server_default = "20"))
    op.add_column('user_record_13_05_2024', sa.Column('map_size', sa.Integer(), nullable=False, server_default = "20"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_record_13_05_2024', sa.Column('map', sa.INTEGER(), server_default=sa.text("'20'"), nullable=False))
    op.add_column('cell_13_05_2024', sa.Column('map', sa.INTEGER(), server_default=sa.text("'20'"), nullable=False))
    op.drop_column('cell_13_05_2024', 'map_size')
    op.drop_column('user_record_13_05_2024', 'map_size')

    # ### end Alembic commands ###
